ADD pdf reading as an input option
SkBlaz/rakun2 pull request #2
Opened 2022-12-05 10:10 UTC by bkolosk1

2022-12-05 15:32 UTC, SkBlaz requested changes

2022-12-05 15:32 UTC, SkBlaz commented on requirements.txt
> +pymupdf
Add exact version please

2022-12-05 15:32 UTC, SkBlaz commented on rakun2/class_rakun.py
> +            with fitz.open(document) as doc:
add encoding

2022-12-05 15:32 UTC, SkBlaz commented on rakun2/class_rakun.py
> +            with fitz.open(document) as doc:
+ maybe an example in `examples`?

2022-12-07 09:19 UTC, bkolosk1 commented on requirements.txt
> +pymupdf
Done

2022-12-07 09:19 UTC, bkolosk1 commented on rakun2/class_rakun.py
> +            with fitz.open(document) as doc:
Done

2022-12-07 16:33 UTC, SkBlaz approved these changes

2022-12-07 16:33 UTC, merged